name:   new-post
on:     
  - push
jobs:
  check-and-submit-post:
    if:         ${{ startsWith(github.event.head_commit.message, 'new post:') }}
    runs-on:    ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Grab filenames and construct message
        run: |
            OUT=$( git show --name-only --oneline HEAD )
            FIRST_IMAGE=$( echo "$OUT" | grep '.jpg' | head -n 1 )
            TITLE=$( grep 'title: ' $( echo "$OUT" | grep 'contents.lr$' ) | sed -r 's/^title: (.+)$/\1/' )
            echo "first_image::$FIRST_IMAGE" >> $GITHUB_ENV
            echo "title::$TITLE" >> $GITHUB_ENV

      - uses: snow-actions/tweet@v1.1.0
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: New blog post: ${{ env.title }}
          media_paths: ${{ env.first_image }}

      - run: echo ${{ steps.tweet.outputs.response }}
